id: P8E7FE387
initial_creation_type: ocr
source_metadata:
  volumes:
    fc1d73532f544825b46d824ac141b236:
      base_file: v107.txt
      image_group_id: I1PD95952
      title: དེ་ཁོ་ན་ཉིད་བསྡུས་པའི་དཀའ་འགྲེལ།
      total_pages: 1891
      volume_number: 107
